export const downloadsData = [
  {
    id: "colorful-tajweedi-quran",
    name: "Colorful Tajweedi Quran",
    description: "A beautifully color-coded Quran with Tajweed rules highlighted for easy learning and recitation.",
    image: "/Colorful Tajweedi Quran - 1 downloads.jpeg",
    tag: "Tajweed",
    pdfs: [
      {
        id: "complete-quran",
        name: "Complete Quran",
        description: "Complete Quran with color-coded Tajweed for accurate and easy recitation.",
        pages: "555 pages",
        viewUrl: "https://drive.google.com/file/d/15WFVILlQhoxj0Vl3nmYUDCPQX5IL3eMO/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=15WFVILlQhoxj0Vl3nmYUDCPQX5IL3eMO",
      },
      {
        id: "juz-01",
        name: "Juz 01",
        description: "Read Juz 01 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "20 pages",
        viewUrl: "https://drive.google.com/file/d/1XoJWtO9UFqSTTYd2bq-8Ycejz_MgFPUc/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1XoJWtO9UFqSTTYd2bq-8Ycejz_MgFPUc",
      },
      {
        id: "juz-02",
        name: "Juz 02",
        description: "Read Juz 02 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1omfJWahTQL5HHOIJWaF2Zz_7WLzFSjEL/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1omfJWahTQL5HHOIJWaF2Zz_7WLzFSjEL",
      },
      {
        id: "juz-03",
        name: "Juz 03",
        description: "Read Juz 03 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1234567890/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1234567890",
      },
      {
        id: "juz-04",
        name: "Juz 04",
        description: "Read Juz 04 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1OCrtpopSOA3YTPBLNzkIpFq40MAAa7VL/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1OCrtpopSOA3YTPBLNzkIpFq40MAAa7VL",
      },
      {
        id: "juz-05",
        name: "Juz 05",
        description: "Read Juz 05 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/17vrd5HQ1xxF4zXdYjRUpLrhJQPjUl7yq/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=17vrd5HQ1xxF4zXdYjRUpLrhJQPjUl7yq",
      },
      {
        id: "juz-06",
        name: "Juz 06",
        description: "Read Juz 06 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1MKD0iufbLrtfHG2SUtxNHcMHWkdbfEVZ/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1MKD0iufbLrtfHG2SUtxNHcMHWkdbfEVZ",
      },
      {
        id: "juz-07",
        name: "Juz 07",
        description: "Read Juz 07 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1qTLt3pF7N1HvfpzgVwu668-UKFUMQyzx/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1qTLt3pF7N1HvfpzgVwu668-UKFUMQyzx",
      },
      {
        id: "juz-08",
        name: "Juz 08",
        description: "Read Juz 08 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1HSuYnoyre3mRrTgJ-bwd9PagCVv84tJF/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1HSuYnoyre3mRrTgJ-bwd9PagCVv84tJF",
      },
      {
        id: "juz-09",
        name: "Juz 09",
        description: "Read Juz 09 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1E1qan-WRNVRjoIG4m_8rfoLvn_a6U11k/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1E1qan-WRNVRjoIG4m_8rfoLvn_a6U11k",
      },
      {
        id: "juz-10",
        name: "Juz 10",
        description: "Read Juz 10 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1yQonWMVc4PKTLL5sIKao6Wamp7rM06jR/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1yQonWMVc4PKTLL5sIKao6Wamp7rM06jR",
      },
      {
        id: "juz-11",
        name: "Juz 11",
        description: "Read Juz 11 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/16kh1N3yEH982sQWzNV7o3NLQM1dekEi-/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=16kh1N3yEH982sQWzNV7o3NLQM1dekEi-",
      },
      {
        id: "juz-12",
        name: "Juz 12",
        description: "Read Juz 12 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1UkiW6kfYvH7q-NmB-w_PogpJC8G6Ievd/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1UkiW6kfYvH7q-NmB-w_PogpJC8G6Ievd",
      },
      {
        id: "juz-13",
        name: "Juz 13",
        description: "Read Juz 13 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1msHXb0MzRmIktiESNNGT6xnqj-zmupkR/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1msHXb0MzRmIktiESNNGT6xnqj-zmupkR",
      },
      {
        id: "juz-14",
        name: "Juz 14",
        description: "Read Juz 14 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1GgJovD-8RDCqfqb73wkj-M6tRyFVLqAA/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1GgJovD-8RDCqfqb73wkj-M6tRyFVLqAA",
      },
      {
        id: "juz-15",
        name: "Juz 15",
        description: "Read Juz 15 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1JWHTn0vqtkf0JvcKNPqKWQym2io-wb3N/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1JWHTn0vqtkf0JvcKNPqKWQym2io-wb3N",
      },
      {
        id: "juz-16",
        name: "Juz 16",
        description: "Read Juz 16 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1Ze8w4w-t9zp-xi1Mb81LQ2PUAmCY0YNH/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1Ze8w4w-t9zp-xi1Mb81LQ2PUAmCY0YNH",
      },
      {
        id: "juz-17",
        name: "Juz 17",
        description: "Read Juz 17 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1Od0ST960-W9t3VWq6fF4wdaZunY96Qv0/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1Od0ST960-W9t3VWq6fF4wdaZunY96Qv0",
      },
      {
        id: "juz-18",
        name: "Juz 18",
        description: "Read Juz 18 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1DTO1IfZ3Y5X6isxQ351QnqDv4N-EFQR0/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1DTO1IfZ3Y5X6isxQ351QnqDv4N-EFQR0",
      },
      {
        id: "juz-19",
        name: "Juz 19",
        description: "Read Juz 19 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1MyxXJOkh8hU7kBXp-WpPkWw9gk7Bk5sc/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1MyxXJOkh8hU7kBXp-WpPkWw9gk7Bk5sc",
      },
      {
        id: "juz-20",
        name: "Juz 20",
        description: "Read Juz 20 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1he79dIdBlnL-CC2n8na3SD2IPKADCt7-/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1he79dIdBlnL-CC2n8na3SD2IPKADCt7-",
      },
      {
        id: "juz-21",
        name: "Juz 21",
        description: "Read Juz 21 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1dirb3q8dqErC7GklIknHjJmsZCBKrR89/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1dirb3q8dqErC7GklIknHjJmsZCBKrR89",
      },
      {
        id: "juz-22",
        name: "Juz 22",
        description: "Read Juz 22 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1hvAAMJLlhgSibrxqGfb9xKH3G4sx-c0a/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1hvAAMJLlhgSibrxqGfb9xKH3G4sx-c0a",
      },
      {
        id: "juz-23",
        name: "Juz 23",
        description: "Read Juz 23 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1fVFIWFPb-nfP_Y8dSQp71gs2m2byIDSP/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1fVFIWFPb-nfP_Y8dSQp71gs2m2byIDSP",
      },
      {
        id: "juz-24",
        name: "Juz 24",
        description: "Read Juz 24 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1k3z9ucuQP5je1tayXXGo9Yo-3KoRcOiE/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1k3z9ucuQP5je1tayXXGo9Yo-3KoRcOiE",
      },
      {
        id: "juz-25",
        name: "Juz 25",
        description: "Read Juz 25 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1lF83DsTWioeeq9IHF09UHJOZzNhgiy_9/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1lF83DsTWioeeq9IHF09UHJOZzNhgiy_9",
      },
      {
        id: "juz-26",
        name: "Juz 26",
        description: "Read Juz 26 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1D0qhlLxMgBmamJiXOudysDdr_5rqsKUF/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1D0qhlLxMgBmamJiXOudysDdr_5rqsKUF",
      },
      {
        id: "juz-27",
        name: "Juz 27",
        description: "Read Juz 27 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "18 pages",
        viewUrl: "https://drive.google.com/file/d/1dsuXbYp7lKXrsgE_g315ihenvppH_NQn/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1dsuXbYp7lKXrsgE_g315ihenvppH_NQn",
      },
      {
        id: "juz-28",
        name: "Juz 28",
        description: "Read Juz 28 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "20 pages",
        viewUrl: "https://drive.google.com/file/d/192vi-kgjdRgDdjAvAj5ESpogX971xoSH/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=192vi-kgjdRgDdjAvAj5ESpogX971xoSH",
      },
      {
        id: "juz-29",
        name: "Juz 29",
        description: "Read Juz 29 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "20 pages",
        viewUrl: "https://drive.google.com/file/d/1zLmQduUu_I1sWuWJD2Uo9C1l_V0ni_XB/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1zLmQduUu_I1sWuWJD2Uo9C1l_V0ni_XB",
      },
      {
        id: "juz-30",
        name: "Juz 30",
        description: "Read Juz 30 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "22 pages",
        viewUrl: "https://drive.google.com/file/d/1-UyocJoNWdelJsbjWk5ybSvSY4MSmK_0/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1-UyocJoNWdelJsbjWk5ybSvSY4MSmK_0",
      },
    ],
  },
  {
    id: "english-quran-word-to-word-translation",


    name: "English Quran Word to Word Translation",
    description: "A comprehensive word-by-word English translation of the Quran to help understand the meaning of every verse.",
    image: "/English Quran Word to word Translation - 2 downloads.jpeg",
    tag: "Translation",
    pdfs: [
      {
        id: "juz-01",
        name: "Juz 01",
        description: "Read Juz 01 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "57 pages",
        viewUrl: "https://drive.google.com/file/d/1jWZsuUoNykcv5ISaImfIHpjLXs2QtAhK/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1jWZsuUoNykcv5ISaImfIHpjLXs2QtAhK",
      },
      {
        id: "juz-02",
        name: "Juz 02",
        description: "Read Juz 02 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "58 pages",
        viewUrl: "https://drive.google.com/file/d/1ePDgyLd2MxSYLkZxZSXDKsFzSOk42ANj/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1ePDgyLd2MxSYLkZxZSXDKsFzSOk42ANj",
      },
      {
        id: "juz-03",
        name: "Juz 03",
        description: "Read Juz 03 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "57 pages",
        viewUrl: "https://drive.google.com/file/d/1R9FtOY21cybSFGi07pwj6kESZfeTRuc3/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1R9FtOY21cybSFGi07pwj6kESZfeTRuc3",
      },
      {
        id: "juz-04",
        name: "Juz 04",
        description: "Read Juz 04 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "56 pages",
        viewUrl: "https://drive.google.com/file/d/1vnllO1z-4D2mmMcCDTG_GmVOcmCRZPCT/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1vnllO1z-4D2mmMcCDTG_GmVOcmCRZPCT",
      },
      {
        id: "juz-05",
        name: "Juz 05",
        description: "Read Juz 05 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "55 pages",
        viewUrl: "https://drive.google.com/file/d/1lB48Tt6zO-vXsBsqNrQ1I1__iC-qRTld/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1lB48Tt6zO-vXsBsqNrQ1I1__iC-qRTld",
      },
      {
        id: "juz-06",
        name: "Juz 06",
        description: "Read Juz 06 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "55 pages",
        viewUrl: "https://drive.google.com/file/d/1_cu3aNWGT6UU7d7KtiGsjytV5Z7iDmuA/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1_cu3aNWGT6UU7d7KtiGsjytV5Z7iDmuA",
      },
      {
        id: "juz-07",
        name: "Juz 07",
        description: "Read Juz 07 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "59 pages",
        viewUrl: "https://drive.google.com/file/d/1bcagilfuiNf5Rqc-CUxZ7WAmjbUJ3SQa/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1bcagilfuiNf5Rqc-CUxZ7WAmjbUJ3SQa",
      },
      {
        id: "juz-08",
        name: "Juz 08",
        description: "Read Juz 08 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "58 pages",
        viewUrl: "https://drive.google.com/file/d/1-gam1y4w9CQ_Xgtb-d-L3JgvHGuNQoWf/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1-gam1y4w9CQ_Xgtb-d-L3JgvHGuNQoWf",
      },
      {
        id: "juz-09",
        name: "Juz 09",
        description: "Read Juz 09 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "56 pages",
        viewUrl: "https://drive.google.com/file/d/1-rqAlOXI6u9z7bWDt6UJyt-yns-AG9kQ/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1-rqAlOXI6u9z7bWDt6UJyt-yns-AG9kQ",
      },
      {
        id: "juz-10",
        name: "Juz 10",
        description: "Read Juz 10 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "56 pages",
        viewUrl: "https://drive.google.com/file/d/1cXyrkOZbroGMl_UYp_aAUeYJ0YtNsmrb/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1cXyrkOZbroGMl_UYp_aAUeYJ0YtNsmrb",
      },
      {
        id: "juz-11",
        name: "Juz 11",
        description: "Read Juz 11 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "59 pages",
        viewUrl: "https://drive.google.com/file/d/1Wdvy27jhBiIwTPa-suqVhDkC1B5Xx2YX/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1Wdvy27jhBiIwTPa-suqVhDkC1B5Xx2YX",
      },
      {
        id: "juz-12",
        name: "Juz 12",
        description: "Read Juz 12 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "59 pages",
        viewUrl: "https://drive.google.com/file/d/1JhQ39pBxdw1hbZmXgfFtTeMqVCY4g8i_/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1JhQ39pBxdw1hbZmXgfFtTeMqVCY4g8i_",
      },
      {
        id: "juz-13",
        name: "Juz 13",
        description: "Read Juz 13 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "58 pages",
        viewUrl: "https://drive.google.com/file/d/1v9BMEAhmG8VHt8brDNacG01o_8Hl9c1k/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1v9BMEAhmG8VHt8brDNacG01o_8Hl9c1k",
      },
      {
        id: "juz-14",
        name: "Juz 14",
        description: "Read Juz 14 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "58 pages",
        viewUrl: "https://drive.google.com/file/d/1550Lw1wECpddBMEmPz6N2SNNHNkxRFiP/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1550Lw1wECpddBMEmPz6N2SNNHNkxRFiP",
      },
      {
        id: "juz-15",
        name: "Juz 15",
        description: "Read Juz 15 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "62 pages",
        viewUrl: "https://drive.google.com/file/d/1uhoF7GQiiAn3u2VyvyvNum5Z3ABrRjvL/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1uhoF7GQiiAn3u2VyvyvNum5Z3ABrRjvL",
      },
      {
        id: "juz-16",
        name: "Juz 16",
        description: "Read Juz 16 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "63 pages",
        viewUrl: "https://drive.google.com/file/d/1s3b0o4ShEw50IPYV-ORHdV_GpvY8ET_p/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1s3b0o4ShEw50IPYV-ORHdV_GpvY8ET_p",
      },
      {
        id: "juz-17",
        name: "Juz 17",
        description: "Read Juz 17 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "55 pages",
        viewUrl: "https://drive.google.com/file/d/1QihpBdehGj1cSOIagLj-RIFK5nxa9V4p/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1QihpBdehGj1cSOIagLj-RIFK5nxa9V4p",
      },
      {
        id: "juz-18",
        name: "Juz 18",
        description: "Read Juz 18 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "59 pages",
        viewUrl: "https://drive.google.com/file/d/1jwLX1o5n3z1kgpRM60kUIsBhH2ioI_ac/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1jwLX1o5n3z1kgpRM60kUIsBhH2ioI_ac",
      },
      {
        id: "juz-19",
        name: "Juz 19",
        description: "Read Juz 19 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "60 pages",
        viewUrl: "https://drive.google.com/file/d/1VsstHywSL5XncrMKbJ7r1ldgVRgZorLz/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1VsstHywSL5XncrMKbJ7r1ldgVRgZorLz",
      },
      {
        id: "juz-20",
        name: "Juz 20",
        description: "Read Juz 20 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "56 pages",
        viewUrl: "https://drive.google.com/file/d/159ogEOKjRz7hrAahuG0PRFu7Jbk_M_iu/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=159ogEOKjRz7hrAahuG0PRFu7Jbk_M_iu",
      },
      {
        id: "juz-21",
        name: "Juz 21",
        description: "Read Juz 21 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "58 pages",
        viewUrl: "https://drive.google.com/file/d/1gRUI9zWrcKrxIMSH3E2GhYJ1TDNYKwHi/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1gRUI9zWrcKrxIMSH3E2GhYJ1TDNYKwHi",
      },
      {
        id: "juz-22",
        name: "Juz 22",
        description: "Read Juz 22 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "58 pages",
        viewUrl: "https://drive.google.com/file/d/1EUV5krDVPU-gnnYOc8awXEV3PTUJxEYK/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1EUV5krDVPU-gnnYOc8awXEV3PTUJxEYK",
      },
      {
        id: "juz-23",
        name: "Juz 23",
        description: "Read Juz 23 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "59 pages",
        viewUrl: "https://drive.google.com/file/d/1FlWuEyPdAcE--DmgUTyN8DKkEWmp5baf/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1FlWuEyPdAcE--DmgUTyN8DKkEWmp5baf",
      },
      {
        id: "juz-24",
        name: "Juz 24",
        description: "Read Juz 24 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "55 pages",
        viewUrl: "https://drive.google.com/file/d/1ecohGmcCupozdulb_jGKfGauFYxB9xj4/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1ecohGmcCupozdulb_jGKfGauFYxB9xj4",
      },
      {
        id: "juz-25",
        name: "Juz 25",
        description: "Read Juz 25 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "60 pages",
        viewUrl: "https://drive.google.com/file/d/1KPvg0l4veq69uWgG3EaJvO4N6Fm9yGlP/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1KPvg0l4veq69uWgG3EaJvO4N6Fm9yGlP",
      },
      {
        id: "juz-26",
        name: "Juz 26",
        description: "Read Juz 26 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "60 pages",
        viewUrl: "https://drive.google.com/file/d/1a5WU4Ohiz4kyTeX6SpGgtXphRkp7T96E/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1a5WU4Ohiz4kyTeX6SpGgtXphRkp7T96E",
      },
      {
        id: "juz-27",
        name: "Juz 27",
        description: "Read Juz 27 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "62 pages",
        viewUrl: "https://drive.google.com/file/d/19sY744r_FSZhdJCaT2u4K_iiSU5JrGen/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=19sY744r_FSZhdJCaT2u4K_iiSU5JrGen",
      },
      {
        id: "juz-28",
        name: "Juz 28",
        description: "Read Juz 28 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "61 pages",
        viewUrl: "https://drive.google.com/file/d/1F5qKkoZkDzYYbL3IANmrwH3Y5oxtediX/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1F5qKkoZkDzYYbL3IANmrwH3Y5oxtediX",
      },
      {
        id: "juz-29",
        name: "Juz 29",
        description: "Read Juz 29 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "65 pages",
        viewUrl: "https://drive.google.com/file/d/1ORFyY1BSH2V5R5pBlMWlvxeD8ZE9rEWj/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1ORFyY1BSH2V5R5pBlMWlvxeD8ZE9rEWj",
      },
      {
        id: "juz-30",
        name: "Juz 30",
        description: "Read Juz 30 with color-coded Tajweed for smooth and accurate recitation.",
        pages: "67 pages",
        viewUrl: "https://drive.google.com/file/d/1FM-RlXnBAs9qoLgWkPHdO2Tpa_t8rPnc/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1FM-RlXnBAs9qoLgWkPHdO2Tpa_t8rPnc",
      },
    ],
  },
  {
    id: "english-quranic-qaidah",
    name: "English Quranic Qaidah",
    description: "A beginner-friendly Qaidah guide in English to help new learners start reading the Quran correctly.",
    image: "/English Quranic Qaidah - 3 downloads.jpeg",
    tag: "Beginner",
    pdfs: [
      {
        id: "english-qaidah",
        name: "English Qaidah",
        description: "Step-by-step Qaidah guide for beginners learning Quran in English.",
        pages: "71 pages",
        viewUrl: "https://drive.google.com/file/d/1ZrsUs24n-0RO6fx5Wuhlsnj00QNvibXd/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1ZrsUs24n-0RO6fx5Wuhlsnj00QNvibXd",
      },
    ],
  },
  {
    id: "six-kalimas",
    name: "Six Kalima's",
    description: "The six essential Kalimas every Muslim should know, with Arabic text, transliteration, and translation.",
    image: "/Six Kalima's - 4 downloads.jpeg",
    tag: "Basics",
    pdfs: [
      {
        id: "six-kalimas-full",
        name: "Six Kalma's",
        description: "All six Kalimas with Arabic, transliteration, and English translation.",
        pages: "2 pages",
        viewUrl: "https://drive.google.com/file/d/19x18UhFucj1FIVnqXfspo_cvIfgKqH06/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=19x18UhFucj1FIVnqXfspo_cvIfgKqH06",
      },
    ],
  },
  {
    id: "namaz",
    name: "Namaz",
    description: "A complete guide to Salah (Namaz) including steps, duas, and rules for performing the daily prayers correctly.",
    image: "/Namaz - 5 downloads.jpeg",
    tag: "Prayer",
    pdfs: [
      {
        id: "complete-namaz",
        name: "Complete Namaz",
        description: "Complete illustrated guide to performing Salah with all duas and steps.",
        pages: "3 pages",
        viewUrl: "https://drive.google.com/file/d/1zgXy8ygo5tWRii7-jceEMh2E7OjI1ykY/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1zgXy8ygo5tWRii7-jceEMh2E7OjI1ykY",
      },
    ],
  },
  {
    id: "essential-duas",
    name: "Essential Duas in the Life of a Muslim",
    description: "A collection of essential daily duas every Muslim should memorize for morning, evening, and everyday situations.",
    image: "/Essential Duas in the life of a Muslim - 6 downloads.jpeg",
    tag: "Duas",
    pdfs: [
      {
        id: "daily-life-duas",
        name: "Daily Life Duas",
        description: "Daily duas for morning, evening, meals, travel, and more.",
        pages: "11 pages",
        viewUrl: "https://drive.google.com/file/d/1rO63sKceqSOjdNZ1XQgj3q6fe_FaV99q/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1rO63sKceqSOjdNZ1XQgj3q6fe_FaV99q",
      },
    ],
  },
  {
    id: "ramadan-planner",
    name: "Ramadan Planner",
    description: "A structured Ramadan planner to help you make the most of the blessed month with daily goals and ibadah tracking.",
    image: "/Ramdan Planner - 7 downloads.jpeg",
    tag: "Ramadan",
    pdfs: [
      {
        id: "ramadan-planner",
        name: "Ramadan Planner",
        description: "Daily planner for Ramadan with ibadah tracker, goals, and reflection pages.",
        pages: "44 pages",
        viewUrl: "https://drive.google.com/file/d/1rMfXqu6kb--QReb0VKhM5TmsYV3kjYg8/preview",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1rMfXqu6kb--QReb0VKhM5TmsYV3kjYg8",
      },
    ],
  },
];

export type DownloadCategory = (typeof downloadsData)[0];
export type DownloadPdf = DownloadCategory["pdfs"][0];
